<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.1 on win32)" generated="20200130 10:53:42.244" rpa="false">
<suite id="s1" name="CalendraTest" source="C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\tests\CalendraTest.robot">
<test id="s1-t1" name="Type in search query field">
<kw name="Init Driver" type="setup">
<msg timestamp="20200130 10:53:42.307" level="FAIL">No keyword with name 'Init Driver' found.</msg>
<status status="FAIL" starttime="20200130 10:53:42.307" endtime="20200130 10:53:42.307"></status>
</kw>
<status status="FAIL" starttime="20200130 10:53:42.306" endtime="20200130 10:53:42.308" critical="yes">Setup failed:
No keyword with name 'Init Driver' found.</status>
</test>
<doc>Suite description</doc>
<status status="FAIL" starttime="20200130 10:53:42.246" endtime="20200130 10:53:42.308"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="CalendraTest">CalendraTest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200130 10:53:42.281" level="ERROR">Error in file 'C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\resource\resource.robot': Importing test library 'C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\steps\BaseSteps.py' failed: ModuleNotFoundError: No module named 'appium'
Traceback (most recent call last):
  File "C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\steps\BaseSteps.py", line 5, in &lt;module&gt;
    from framework.mobile.driver.MobileDriver import MobileDriver
  File "C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\framework\mobile\driver\MobileDriver.py", line 2, in &lt;module&gt;
    from appium.webdriver import Remote
PYTHONPATH:
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5
  C:\Users\Nurlan.Rahimzada\AppData\Local\Programs\Python\Python38-32\Scripts\robot.exe
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\tests
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\python38.zip
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\DLLs
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\lib
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\lib\site-packages</msg>
<msg timestamp="20200130 10:53:42.306" level="ERROR">Error in file 'C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\resource\resource.robot': Importing test library 'C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\steps\AppSteps.py' failed: ModuleNotFoundError: No module named 'appium'
Traceback (most recent call last):
  File "C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\steps\AppSteps.py", line 3, in &lt;module&gt;
    from project.mobile.screens.CalendarScreen import CalendarScreen
  File "C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\screens\CalendarScreen.py", line 1, in &lt;module&gt;
    from appium.webdriver.common.mobileby import MobileBy
PYTHONPATH:
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5
  C:\Users\Nurlan.Rahimzada\AppData\Local\Programs\Python\Python38-32\Scripts\robot.exe
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5
  C:\Users\Nurlan.Rahimzada\Documents\Python\selenium_robot-11c511cfb3a8ab9778da056221c171f7457dfcd5\project\mobile\tests
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\python38.zip
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\DLLs
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\lib
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32
  c:\users\nurlan.rahimzada\appdata\local\programs\python\python38-32\lib\site-packages</msg>
</errors>
</robot>
